name: Published Canary Package
on:
  push:
    tags: ['*-canary.*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.0
      - uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: |
          pnpm install --frozen-lockfile
          pnpm build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
